export const DOMAIN_ERROR_CODES = {
  INVALID_DOCUMENT_STATE: 'INVALID_DOCUMENT_STATE',
  OPERATION_DENIED: 'OPERATION_DENIED',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  DUPLICATE_ITEM: 'DUPLICATE_ITEM',
  INVALID_ITEM_QUANTITY: 'INVALID_ITEM_QUANTITY',
  INVALID_ITEM_PRICE: 'INVALID_ITEM_PRICE',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT',
  INVALID_CANCEL_REASON: 'INVALID_CANCEL_REASON',
  INVALID_ADJUSTMENT_REASON: 'INVALID_ADJUSTMENT_REASON',
  OWNERSHIP_DENIED: 'OWNERSHIP_DENIED',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  DOCUMENT_ALREADY_CONFIRMED: 'DOCUMENT_ALREADY_CONFIRMED',
  DOCUMENT_ALREADY_CANCELLED: 'DOCUMENT_ALREADY_CANCELLED',
  DOCUMENT_ALREADY_INVOICED: 'DOCUMENT_ALREADY_INVOICED',
  INVOICE_NOT_ALLOWED: 'INVOICE_NOT_ALLOWED',
  INVALID_DOCUMENT_NUMBER_FORMAT: 'INVALID_DOCUMENT_NUMBER_FORMAT',
  INVALID_DOCUMENT_NUMBER_TYPE: 'INVALID_DOCUMENT_NUMBER_TYPE',
} as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];

export interface DomainError {
  code: DomainErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
