export const APPLICATION_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_CUSTOMER_ID: 'REQUIRED_CUSTOMER_ID',
  CUSTOMER_NOT_AVAILABLE: 'CUSTOMER_NOT_AVAILABLE',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_CONTACT_NOT_FOUND: 'CUSTOMER_CONTACT_NOT_FOUND',
  CUSTOMER_ADDRESS_NOT_FOUND: 'CUSTOMER_ADDRESS_NOT_FOUND',
  DUPLICATE_CUSTOMER_DOCUMENT: 'DUPLICATE_CUSTOMER_DOCUMENT',
  REQUIRED_REPRESENTED_COMPANY: 'REQUIRED_REPRESENTED_COMPANY',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_NOT_QUOTE: 'DOCUMENT_NOT_QUOTE',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT_ALREADY_CONFIRMED: 'CONFLICT_ALREADY_CONFIRMED',
  DOMAIN_OPERATION_FAILED: 'DOMAIN_OPERATION_FAILED',
} as const;

export type ApplicationErrorCode = (typeof APPLICATION_ERROR_CODES)[keyof typeof APPLICATION_ERROR_CODES];

export interface ApplicationError {
  code: ApplicationErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
