export const APPLICATION_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_CUSTOMER_ID: 'REQUIRED_CUSTOMER_ID',
  CUSTOMER_NOT_AVAILABLE: 'CUSTOMER_NOT_AVAILABLE',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_CONTACT_NOT_FOUND: 'CUSTOMER_CONTACT_NOT_FOUND',
  CUSTOMER_ADDRESS_NOT_FOUND: 'CUSTOMER_ADDRESS_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRICE_TABLE_NOT_FOUND: 'PRICE_TABLE_NOT_FOUND',
  PRICE_TABLE_ITEM_NOT_FOUND: 'PRICE_TABLE_ITEM_NOT_FOUND',
  CUSTOMER_PRODUCT_PRICE_OVERRIDE_NOT_FOUND: 'CUSTOMER_PRODUCT_PRICE_OVERRIDE_NOT_FOUND',
  DUPLICATE_ACTIVE_CUSTOMER_PRODUCT_PRICE_OVERRIDE: 'DUPLICATE_ACTIVE_CUSTOMER_PRODUCT_PRICE_OVERRIDE',
  PRICE_NOT_RESOLVABLE: 'PRICE_NOT_RESOLVABLE',
  PAYMENT_TERM_NOT_FOUND: 'PAYMENT_TERM_NOT_FOUND',
  DUPLICATE_CUSTOMER_DOCUMENT: 'DUPLICATE_CUSTOMER_DOCUMENT',
  DUPLICATE_PRODUCT_SKU: 'DUPLICATE_PRODUCT_SKU',
  DUPLICATE_PRICE_TABLE: 'DUPLICATE_PRICE_TABLE',
  DUPLICATE_PRICE_TABLE_ITEM_PERIOD: 'DUPLICATE_PRICE_TABLE_ITEM_PERIOD',
  DUPLICATE_PAYMENT_TERM: 'DUPLICATE_PAYMENT_TERM',
  REQUIRED_REPRESENTED_COMPANY: 'REQUIRED_REPRESENTED_COMPANY',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_NOT_QUOTE: 'DOCUMENT_NOT_QUOTE',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT_ALREADY_CONFIRMED: 'CONFLICT_ALREADY_CONFIRMED',
  DOMAIN_OPERATION_FAILED: 'DOMAIN_OPERATION_FAILED',
} as const;

export type ApplicationErrorCode = (typeof APPLICATION_ERROR_CODES)[keyof typeof APPLICATION_ERROR_CODES];

export interface ApplicationError {
  code: ApplicationErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
